baseURL = 'https://d4nielcosta.github.io/markdown-editor/'
languageCode = 'en-gb'
title = 'Markdown Viewer'
theme = 'hugo-theme-basic'

enableEmoji = true

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[params]
titleEmoji = ":tada:"

[Permalinks]
post = "posts/:slug"

[[params.menu]]
name = "posts"
url = "posts/"